package com.graduation.pro.study_system.util;

public class WeatherInfo {
	private int year;
	private int month;
	private int day;
	private float TongNan;
	private float HeChuan;
	private float TongLiang;
	private float DaZu;
	private float BeiPei;
	private float BiShan;
	private float YuBei;
	private float ChangShou;
	private float RongCang;
	private float YongChuan;
	private float JiangJin;
	private float BaNan;
	private float ShaPinBa;
	private float YinJiang;
	private float WanShen;
	private float NanChuan;
	private float PeiLing;
	private float WuLong;
	private float FengDu;
	private float DianJiang;
	private float ZhongXian;
	private float LiangPin;
	private float WanZhon;
	private float YunYang;
	private float KaiXian;
	private float FengJie;
	private float WuShan;
	private float WuXi;
	private float ChenKou;
	private float XiuShan;
	private float YouYang;
	private float PengShui;
	private float QinJiang;
	private float ShiZhu;
}
